### ISSUE TITLE
Build/run on Ubuntu20.04

### ISSUE THREAD

**Issue by eschulte** [utds3lab/multiverse#10]
Hi,

I'm able to build multiverse on Ubuntu20.04 in a Docker image with the following Dockerfile:
```Dockerfile
FROM ubuntu:20.04

SHELL ["/bin/bash", "-c"]

# Install apt packages
RUN export DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN apt-get -y update && \
    apt-get -y install autoconf build-essential gcc-multilib g++-multilib \
    git curl python-is-python2
RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
RUN python2 get-pip.py
RUN pip2 install pwntools pyelftools pathlib2

# Clone and build
RUN git clone https://github.com/utds3lab/multiverse.git
RUN git clone https://github.com/baumane/capstone.git /multiverse/capstone
RUN git clone https://github.com/schieb/ELFManip.git /multiverse/ELFManip

WORKDIR /multiverse/ELFManip
RUN python setup.py install

WORKDIR /multiverse/capstone
RUN make
WORKDIR /multiverse/capstone/bindings/python
RUN make install

WORKDIR /multiverse
RUN make
```
however, when I go to run multiverse as specified in the README I get the following error.
```
root@fcb76c818f7d:/multiverse# ./multiverse.py --execonly --arch x86-64 simplest64
Found .text
Writing ONLY main binary, without support for rewritten .so files
Base address: 0x1000
Generating mapping...
Starting disassembly...
Disassembly 0% complete...
Disassembly 10% complete...
Disassembly 20% complete...
Disassembly 30% complete...
Disassembly 40% complete...
Disassembly 50% complete...
Disassembly 60% complete...
Disassembly 70% complete...
Disassembly 80% complete...
Disassembly 90% complete...
Disassembly 100% complete...
final offset for mapping is: 0xbee
Generating new code...
Starting disassembly...
Disassembly 0% complete...
Disassembly 10% complete...
Disassembly 20% complete...
Disassembly 30% complete...
Disassembly 40% complete...
Disassembly 50% complete...
Disassembly 60% complete...
Disassembly 70% complete...
Disassembly 80% complete...
Disassembly 90% complete...
Disassembly 100% complete...
Traceback (most recent call last):
  File "./multiverse.py", line 317, in <module>
    rewriter.rewrite(args.filename,args.arch)
  File "./multiverse.py", line 192, in rewrite
    newbytes = mapper.gen_newcode(mapping)
  File "/multiverse/brute_force_mapper.py", line 132, in gen_newcode
    newbytes+=self.runtime.get_auxvec_code(mapping[self.entry])
KeyError: 4192
root@fcb76c818f7d:/multiverse#
```

Is multiverse expected to run on Ubuntu20.04?  Can you shed any light as to what is going wrong here?

Thanks!

**Comment by baumane** [comment]
Multiverse was originally tested on Ubuntu 14.04, and has never been tested on Ubuntu 20.04, so it's possible there may be compatibility issues.  It may be worth testing with an older version of Ubuntu to make sure this issue isn't caused by that.

I'm not sure what could be causing that particular error.  I looks like there is no entry in the mapping (from original addresses to rewritten addresses) for the binary's entry point, which is strange.  The value given in the error of 4192 translates to 0x1060 in hex.  Is that the entry point address in your simplest64 binary?  In brute_force_mapper.py, function gen_mapping, you could add a print statement to check what entries are being added to the mapping at line 68.

**Comment by eschulte** [comment]
Thanks for the follow up.  Yes, 0x1060 is the entry point for my simplest64 binary.
```
$ readelf -h simplest64
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x1060
  Start of program headers:          64 (bytes into file)
  Start of section headers:          14752 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         13
  Size of section headers:           64 (bytes)
  Number of section headers:         31
  Section header string table index: 30
```
With the following change
```shell
sed -i '68 i\\tprint "mapping[%s] -> 0x%x" % (k, offset)' brute_force_mapper.py
```
I get the following mappings
```
mapping[4099] -> 0x79
mapping[4100] -> 0x7a
mapping[4104] -> 0x7e
mapping[4111] -> 0x85
mapping[4114] -> 0x88
mapping[4116] -> 0x8e
mapping[4118] -> 0xae
mapping[4122] -> 0xb2
mapping[4123] -> 0xcb
mapping[4125] -> 0xcd
mapping[4127] -> 0xcf
mapping[4129] -> 0xd1
mapping[4134] -> 0xd6
mapping[4141] -> 0xdd
mapping[4101] -> 0xe5
mapping[4102] -> 0xed
mapping[4103] -> 0xee
mapping[4106] -> 0xf1
mapping[4105] -> 0xfb
mapping[4107] -> 0x106
mapping[4109] -> 0x108
mapping[4110] -> 0x10f
mapping[4113] -> 0x112
mapping[4112] -> 0x11c
mapping[4115] -> 0x123
mapping[4117] -> 0x125
mapping[4119] -> 0x12d
mapping[4121] -> 0x135
mapping[4124] -> 0x13c
mapping[4126] -> 0x13e
mapping[4128] -> 0x140
mapping[4132] -> 0x14b
mapping[4133] -> 0x152
mapping[4135] -> 0x154
mapping[4136] -> 0x178
mapping[4137] -> 0x182
mapping[4139] -> 0x183
mapping[4140] -> 0x18a
mapping[4143] -> 0x191
mapping[4147] -> 0x193
mapping[4148] -> 0x194
mapping[4153] -> 0x199
mapping[4159] -> 0x19f
mapping[4149] -> 0x1a5
mapping[4151] -> 0x1a7
mapping[4150] -> 0x1ae
mapping[4152] -> 0x1b0
mapping[4154] -> 0x1b2
mapping[4155] -> 0x1bc
mapping[4158] -> 0x1be
mapping[4164] -> 0x1e2
mapping[4171] -> 0x1e9
mapping[4163] -> 0x1f3
mapping[4165] -> 0x1f9
mapping[4166] -> 0x21d
mapping[4167] -> 0x227
mapping[4169] -> 0x228
mapping[4170] -> 0x22f
mapping[4173] -> 0x236
mapping[4174] -> 0x239
mapping[4175] -> 0x23b
mapping[4179] -> 0x23d
mapping[4180] -> 0x23e
mapping[4187] -> 0x245
mapping[4181] -> 0x24f
mapping[4182] -> 0x273
mapping[4183] -> 0x27d
mapping[4185] -> 0x283
mapping[4186] -> 0x28a
mapping[4189] -> 0x291
mapping[4190] -> 0x294
mapping[4191] -> 0x296
mapping[4195] -> 0x298
mapping[4196] -> 0x299
mapping[4198] -> 0x29b
mapping[4201] -> 0x29e
mapping[4202] -> 0x29f
mapping[4205] -> 0x2a2
mapping[4209] -> 0x2a6
mapping[4210] -> 0x2a7
mapping[4211] -> 0x2a8
mapping[4218] -> 0x2af
mapping[4225] -> 0x2b6
mapping[4232] -> 0x2bd
mapping[4238] -> 0x2e1
mapping[4239] -> 0x2e2
mapping[4240] -> 0x2e3
mapping[4247] -> 0x2ea
mapping[4254] -> 0x2f1
mapping[4257] -> 0x2f4
mapping[4259] -> 0x2fa
mapping[4266] -> 0x301
mapping[4269] -> 0x304
mapping[4271] -> 0x30a
mapping[4273] -> 0x325
mapping[4280] -> 0x32c
mapping[4281] -> 0x345
mapping[4288] -> 0x34c
mapping[4295] -> 0x353
mapping[4302] -> 0x35a
mapping[4305] -> 0x35d
mapping[4308] -> 0x360
mapping[4312] -> 0x364
mapping[4316] -> 0x368
mapping[4319] -> 0x36b
mapping[4322] -> 0x36e
mapping[4324] -> 0x374
mapping[4331] -> 0x37b
mapping[4334] -> 0x37e
mapping[4336] -> 0x384
mapping[4338] -> 0x39f
mapping[4344] -> 0x3a5
mapping[4345] -> 0x3be
mapping[4197] -> 0x3ca
mapping[4199] -> 0x3d0
mapping[4200] -> 0x3d7
mapping[4203] -> 0x3da
mapping[4204] -> 0x3e1
mapping[4206] -> 0x3e3
mapping[4207] -> 0x3eb
mapping[4212] -> 0x3f2
mapping[4213] -> 0x3fd
mapping[4214] -> 0x407
mapping[4216] -> 0x40d
mapping[4215] -> 0x414
mapping[4217] -> 0x416
mapping[4220] -> 0x419
mapping[4219] -> 0x423
mapping[4221] -> 0x42e
mapping[4223] -> 0x430
mapping[4222] -> 0x437
mapping[4224] -> 0x439
mapping[4227] -> 0x43c
mapping[4226] -> 0x446
mapping[4228] -> 0x451
mapping[4229] -> 0x452
mapping[4231] -> 0x454
mapping[4233] -> 0x456
mapping[4230] -> 0x460
mapping[4234] -> 0x467
mapping[4236] -> 0x468
mapping[4237] -> 0x46f
mapping[4241] -> 0x476
mapping[4242] -> 0x481
mapping[4243] -> 0x48b
mapping[4245] -> 0x491
mapping[4246] -> 0x498
mapping[4249] -> 0x49b
mapping[4248] -> 0x4a5
mapping[4250] -> 0x4b0
mapping[4252] -> 0x4b6
mapping[4253] -> 0x4bd
mapping[4256] -> 0x4c0
mapping[4255] -> 0x4c6
mapping[4258] -> 0x4cd
mapping[4260] -> 0x4d7
mapping[4261] -> 0x4e2
mapping[4264] -> 0x4ec
mapping[4265] -> 0x4f3
mapping[4268] -> 0x4f6
mapping[4267] -> 0x500
mapping[4270] -> 0x507
mapping[4272] -> 0x509
mapping[4275] -> 0x510
mapping[4278] -> 0x513
mapping[4276] -> 0x51a
mapping[4277] -> 0x521
mapping[4279] -> 0x523
mapping[4283] -> 0x52a
mapping[4286] -> 0x52d
mapping[4284] -> 0x534
mapping[4285] -> 0x53b
mapping[4287] -> 0x53d
mapping[4290] -> 0x540
mapping[4289] -> 0x54a
mapping[4293] -> 0x555
mapping[4294] -> 0x55c
mapping[4297] -> 0x55f
mapping[4296] -> 0x569
mapping[4300] -> 0x574
mapping[4301] -> 0x57b
mapping[4304] -> 0x57e
mapping[4303] -> 0x586
mapping[4306] -> 0x58d
mapping[4309] -> 0x594
mapping[4310] -> 0x59c
mapping[4313] -> 0x5a2
mapping[4314] -> 0x5aa
mapping[4315] -> 0x5ab
mapping[4317] -> 0x5b3
mapping[4320] -> 0x5ba
mapping[4323] -> 0x5c1
mapping[4325] -> 0x5c3
mapping[4326] -> 0x5ce
mapping[4327] -> 0x5d8
mapping[4332] -> 0x5dd
mapping[4329] -> 0x5e4
mapping[4330] -> 0x5eb
mapping[4333] -> 0x5ee
mapping[4335] -> 0x5f8
mapping[4337] -> 0x5fa
mapping[4339] -> 0x5fc
mapping[4341] -> 0x606
mapping[4342] -> 0x60e
mapping[4343] -> 0x615
mapping[4347] -> 0x61c
mapping[4348] -> 0x61f
mapping[4350] -> 0x626
mapping[4349] -> 0x628
mapping[4351] -> 0x62a
mapping[4355] -> 0x631
mapping[4356] -> 0x632
mapping[4363] -> 0x639
mapping[4365] -> 0x63f
mapping[4366] -> 0x640
mapping[4374] -> 0x648
mapping[4377] -> 0x64b
mapping[4379] -> 0x651
mapping[4386] -> 0x658
mapping[4391] -> 0x662
mapping[4396] -> 0x66c
mapping[4403] -> 0x673
mapping[4404] -> 0x674
mapping[4405] -> 0x68d
mapping[4408] -> 0x690
mapping[4409] -> 0x6a9
mapping[4357] -> 0x6b5
mapping[4362] -> 0x6ba
mapping[4358] -> 0x6c2
mapping[4360] -> 0x6cc
mapping[4361] -> 0x6d3
mapping[4364] -> 0x6da
mapping[4367] -> 0x6dd
mapping[4368] -> 0x6e9
mapping[4373] -> 0x6ee
mapping[4376] -> 0x6f1
mapping[4378] -> 0x6f3
mapping[4380] -> 0x6f5
mapping[4369] -> 0x700
mapping[4371] -> 0x702
mapping[4370] -> 0x709
mapping[4372] -> 0x711
mapping[4375] -> 0x718
mapping[4381] -> 0x71f
mapping[4382] -> 0x729
mapping[4384] -> 0x72b
mapping[4383] -> 0x732
mapping[4385] -> 0x73a
mapping[4387] -> 0x73c
mapping[4395] -> 0x743
mapping[4397] -> 0x745
mapping[4402] -> 0x74a
mapping[4399] -> 0x752
mapping[4400] -> 0x75a
mapping[4401] -> 0x761
mapping[4407] -> 0x768
mapping[4411] -> 0x76f
mapping[4412] -> 0x772
mapping[4414] -> 0x779
mapping[4413] -> 0x77b
mapping[4415] -> 0x77d
mapping[4419] -> 0x784
mapping[4420] -> 0x785
mapping[4421] -> 0x78f
mapping[4424] -> 0x795
mapping[4428] -> 0x797
mapping[4429] -> 0x798
mapping[4432] -> 0x79b
mapping[4430] -> 0x7b9
mapping[4436] -> 0x7c0
mapping[4437] -> 0x7c1
mapping[4441] -> 0x7c5
mapping[4446] -> 0x7ca
mapping[4453] -> 0x7d1
mapping[4458] -> 0x7d6
mapping[4463] -> 0x7db
mapping[4468] -> 0x7e5
mapping[4473] -> 0x7ea
mapping[4477] -> 0x7ee
mapping[4478] -> 0x807
mapping[4438] -> 0x80e
mapping[4439] -> 0x816
mapping[4440] -> 0x817
mapping[4443] -> 0x822
mapping[4445] -> 0x824
mapping[4448] -> 0x827
mapping[4444] -> 0x831
mapping[4447] -> 0x838
mapping[4449] -> 0x843
mapping[4451] -> 0x844
mapping[4452] -> 0x84b
mapping[4454] -> 0x856
mapping[4456] -> 0x858
mapping[4455] -> 0x85f
mapping[4457] -> 0x861
mapping[4459] -> 0x86c
mapping[4461] -> 0x86e
mapping[4460] -> 0x875
mapping[4462] -> 0x877
mapping[4464] -> 0x879
mapping[4469] -> 0x880
mapping[4471] -> 0x882
mapping[4470] -> 0x889
mapping[4472] -> 0x88b
mapping[4474] -> 0x893
mapping[4476] -> 0x89b
mapping[4479] -> 0x8a2
mapping[4483] -> 0x8a3
mapping[4484] -> 0x8a4
mapping[4486] -> 0x8a6
mapping[4493] -> 0x8ad
mapping[4495] -> 0x8af
mapping[4498] -> 0x8b2
mapping[4500] -> 0x8b4
mapping[4503] -> 0x8b7
mapping[4505] -> 0x8b9
mapping[4508] -> 0x8bc
mapping[4509] -> 0x8bd
mapping[4516] -> 0x8c4
mapping[4517] -> 0x8c5
mapping[4520] -> 0x8c8
mapping[4524] -> 0x8cc
mapping[4529] -> 0x8d6
mapping[4533] -> 0x8da
mapping[4535] -> 0x8e0
mapping[4537] -> 0x8e2
mapping[4544] -> 0x8e9
mapping[4547] -> 0x8ec
mapping[4550] -> 0x8ef
mapping[4553] -> 0x8f2
mapping[4557] -> 0x913
mapping[4561] -> 0x917
mapping[4564] -> 0x91a
mapping[4566] -> 0x920
mapping[4570] -> 0x924
mapping[4571] -> 0x925
mapping[4572] -> 0x926
mapping[4574] -> 0x928
mapping[4576] -> 0x92a
mapping[4578] -> 0x92c
mapping[4580] -> 0x92e
mapping[4581] -> 0x947
mapping[4485] -> 0x957
mapping[4487] -> 0x95d
mapping[4488] -> 0x968
mapping[4489] -> 0x972
mapping[4492] -> 0x975
mapping[4490] -> 0x97d
mapping[4491] -> 0x984
mapping[4494] -> 0x98b
mapping[4496] -> 0x991
mapping[4497] -> 0x998
mapping[4499] -> 0x99e
mapping[4501] -> 0x9a4
mapping[4502] -> 0x9ab
mapping[4504] -> 0x9b1
mapping[4506] -> 0x9b7
mapping[4507] -> 0x9be
mapping[4510] -> 0x9c4
mapping[4511] -> 0x9cf
mapping[4512] -> 0x9d9
mapping[4514] -> 0x9db
mapping[4513] -> 0x9e2
mapping[4515] -> 0x9e4
mapping[4518] -> 0x9e7
mapping[4519] -> 0x9ee
mapping[4521] -> 0x9f4
mapping[4522] -> 0x9fc
mapping[4523] -> 0x9fd
mapping[4528] -> 0xa04
mapping[4531] -> 0xa07
mapping[4532] -> 0xa08
mapping[4536] -> 0xa0c
mapping[4530] -> 0xa13
mapping[4539] -> 0xa1b
mapping[4542] -> 0xa1e
mapping[4540] -> 0xa25
mapping[4541] -> 0xa2c
mapping[4543] -> 0xa2e
mapping[4545] -> 0xa37
mapping[4546] -> 0xa3e
mapping[4548] -> 0xa47
mapping[4549] -> 0xa4e
mapping[4551] -> 0xa54
mapping[4552] -> 0xa5b
mapping[4554] -> 0xa5d
mapping[4555] -> 0xa83
mapping[4556] -> 0xa8a
mapping[4559] -> 0xa8d
mapping[4560] -> 0xaa6
mapping[4563] -> 0xaa9
mapping[4558] -> 0xab1
mapping[4562] -> 0xab9
mapping[4567] -> 0xac0
mapping[4569] -> 0xac8
mapping[4573] -> 0xad0
mapping[4575] -> 0xad6
mapping[4577] -> 0xadc
mapping[4579] -> 0xae2
mapping[4582] -> 0xae8
mapping[4583] -> 0xaf2
mapping[4584] -> 0xafb
mapping[4586] -> 0xb03
mapping[4587] -> 0xb05
mapping[4588] -> 0xb07
mapping[4589] -> 0xb09
mapping[4590] -> 0xb0b
mapping[4591] -> 0xb0d
mapping[4595] -> 0xb14
mapping[4596] -> 0xb15
mapping[4597] -> 0xb2e
mapping[4599] -> 0xb30
mapping[4598] -> 0xb37
mapping[4603] -> 0xb3e
mapping[4604] -> 0xb3f
mapping[4608] -> 0xb43
mapping[4612] -> 0xb47
mapping[4605] -> 0xb65
mapping[4606] -> 0xb6d
mapping[4607] -> 0xb6e
mapping[4609] -> 0xb76
mapping[4611] -> 0xb7e
```

I thought maybe the problem was simplest64 being position independent (the default on Ubuntu20), but I get the same error when I recompile with `-no-pie`.

**Comment by baumane** [comment]
Somehow it appears that the superset disassembly skipped the entry point address, but it did create entries for most addresses around it.  From what I recall, the only reason that an address should not be added to the mapping is if it were trimmed because the code sequence it was in ended in an invalid instruction.  Can you show an excerpt of the disassembly at the entry point?  Once the disassembly reaches an unconditional jmp or ret instruction, then that should be far enough.  

If possible, I suggest you also try running Multiverse on Ubuntu 14.04 or 16.04 to check whether the issue is caused by a new OS version.

**Comment by eschulte** [comment]
I tried on Ubuntu 16 with the attached Dockerfile but multiverse failed there as well (text below).  I can't find active Ubuntu 14 apt repositories any more so I'm unable to build an Ubuntu14 based Docker image and thus I can't try anything earlier that Ubuntu 16.

[Dockerfile-16.txt](https://github.com/utds3lab/multiverse/files/6985466/Dockerfile-16.txt)

```
root@dbcab1aee56f:/multiverse# ./multiverse.py --execonly --arch x86-64 simplest64
Found .text
Writing ONLY main binary, without support for rewritten .so files
Base address: 0x400000
Generating mapping...
Starting disassembly...
Disassembly 0% complete...
Traceback (most recent call last):
  File "./multiverse.py", line 317, in <module>
    rewriter.rewrite(args.filename,args.arch)
  File "./multiverse.py", line 191, in rewrite
    mapping = mapper.gen_mapping()
  File "/multiverse/brute_force_mapper.py", line 53, in gen_mapping
    newins = self.translator.translate_one(ins,None) #In this pass, the mapping is incomplete
  File "/multiverse/x64_translator.py", line 144, in translate_one
    code = asm( '%s %s' % (ins.mnemonic, self.replace_rip(ins,mapping,len(ins.bytes) ) ) )
  File "/multiverse/x64_translator.py", line 84, in replace_rip
    disp_size = ins._detail.arch.x86.encoding.disp_size
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 678, in __getattr__
    raise AttributeError(name)
AttributeError: _detail
root@dbcab1aee56f:/multiverse# file simplest64
simplest64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=2d3845fced0c063378f7ced6eb249b7a5ce0e5bc, not stripped
```

**Comment by baumane** [comment]
It appears that one of the packages installed in your Dockerfile via pip (either pwntools, pyelftools, or pathlib2) automatically installs a newer version of Capstone, which overrides the forked version that is manually installed.  If you run `pip uninstall capstone` in the docker container before running multiverse.py, then Multiverse will rewrite `simplest64` without any errors, and the resulting `simplest64-r` binary should run successfully.  I tested this with your Dockerfile and it works after making that change.  Remember that you also will need to set `LD_BIND_NOW=1` before attempting to run the rewritten binaries.

**Comment by eschulte** [comment]
Thanks, this seems to work for me.  For reference the final complete Dockerfile is attached.

[Dockerfile.txt](https://github.com/utds3lab/multiverse/files/7122070/Dockerfile.txt)

Can you explain (or point me to documentation for) why `LD_BIND_NOW=1` is necessary?

**Comment by baumane** [comment]
There's a discussion about why we need `LD_BIND_NOW=1` in section V of the related paper, but the reason is to keep the dynamic linker from redirecting control to dynamically resolved symbols.  Multiverse doesn't rewrite the dynamic linker, and it makes it difficult for multiverse to redirect to rewritten versions of the code when the linker jumps to the resolved address directly.
