### ISSUE TITLE
I am using capstone-3.0.4 on ubuntu 18.04. After installing all the required tools needed for running multiverse, I got the following message during disassembly.

### ISSUE THREAD

**Issue by adhavsureshkumar** [utds3lab/multiverse#7]
`./multiverse.py --execonly --arch x86-64 simplest64 
Found .text
Writing ONLY main binary, without support for rewritten .so files
Base address: 0x0
Generating mapping...
Starting disassembly...
Disassembly 0% complete...
Traceback (most recent call last):
  File "./multiverse.py", line 317, in <module>
    rewriter.rewrite(args.filename,args.arch)
  File "./multiverse.py", line 191, in rewrite
    mapping = mapper.gen_mapping()
  File "/home/adhav/Downloads/multiverse-master/brute_force_mapper.py", line 53, in gen_mapping
    newins = self.translator.translate_one(ins,None) #In this pass, the mapping is incomplete
  File "/home/adhav/Downloads/multiverse-master/x64_translator.py", line 144, in translate_one
    code = asm( '%s %s' % (ins.mnemonic, self.replace_rip(ins,mapping,len(ins.bytes) ) ) )
  File "/home/adhav/Downloads/multiverse-master/x64_translator.py", line 84, in replace_rip
    disp_size = ins._detail.arch.x86.encoding.disp_size
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 675, in __getattr__
    raise AttributeError(name)
AttributeError: _detail
`

**Comment by baumane** [comment]
As the README says, we use a modified version of Capstone to rewrite 64-bit binaries.  Please try rewriting with that version.

While I would like to update Multiverse to work with the most recent version of Capstone, I need access to certain data about instruction encodings for 64-bit binaries (specifically the offset and size of displacements and immediates in instructions).  These fields were not accessible in Capstone at the time, which is why I made a fork.

If or when this changes and the data I need is provided to the python bindings it should not be difficult to update Multiverse to work with the newest version of Capstone.  I have not had time to request these additions be made to Capstone, but if they are added and someone requests it I may have time to update Multiverse to use the newest version.

**Comment by adhavsureshkumar** [comment]
I tried using the capstone which is mentioned in your readme, but still, the same problem persists. Can you tell me exactly which version of the capstone I need to use?. Thank you!.

**Comment by baumane** [comment]
If you use the forked version of Capstone linked in the readme, it should work.  Can you verify that python is using the correct version of Capstone?  If you open a python interactive terminal, then type:
`>>> import capstone`
and
`>>> capstone`
What does it print?

**Comment by wliuxingxiangyu** [comment]
@baumane  hello,I have the same question,can you give me some advice,Thank you in advance!

>>> import capstone
>>> capstone
<module 'capstone' from '/home/mi/.local/lib/python2.7/site-packages/capstone/__init__.pyc'>
>>>
